Abort the configure script if we can't find a perl executable.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -3,13 +3,13 @@ dnl  Configuration input file for Squid
 dnl
 dnl  Duane Wessels, wessels@nlanr.net, February 1996 (autoconf v2.9)
 dnl
-dnl  $Id: configure.in,v 1.205 2000/10/20 23:50:58 hno Exp $
+dnl  $Id: configure.in,v 1.206 2000/11/30 20:44:00 wessels Exp $
 dnl
 dnl
 dnl
 AC_INIT(src/main.c)
 AC_CONFIG_HEADER(include/autoconf.h)
-AC_REVISION($Revision: 1.205 $)dnl
+AC_REVISION($Revision: 1.206 $)dnl
 AC_PREFIX_DEFAULT(/usr/local/squid)
 AC_CONFIG_AUX_DIR(cfgaux)
 
@@ -758,9 +758,15 @@ AC_PATH_PROG(RM, rm, $FALSE)
 AC_PATH_PROG(MV, mv, $FALSE)
 AC_PATH_PROG(MKDIR, mkdir, $FALSE)
 AC_PATH_PROG(LN, ln, cp)
-AC_PATH_PROG(PERL, perl, /usr/local/bin/perl)
+AC_PATH_PROG(PERL, perl, none)
 AC_PATH_PROG(MAKEDEPEND, makedepend, $TRUE)
 AC_PATH_PROG(AR, ar, $FALSE)
+
+if test "$ac_cv_path_PERL" = "none"; then
+	echo "Perl is required to compile Squid"
+	echo "Please install Perl and then re-run configure"
+	exit 1
+fi
 
 case "$host" in
     *-hp-hpux*)
