Windows port: addition of native authentication helpers.
- mswin_auth: 		Basic helper
- mswin_ntlm_auth: 	NTLM helper
- mswin_negotiate_auth: Negotiate helper

Supported build environment:

- Cygwin
- MSYS + MinGW
- MS VisualStudio C++ 2005

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -3,7 +3,7 @@ dnl  Configuration input file for Squid
 dnl
 dnl  Duane Wessels, wessels@nlanr.net, February 1996 (autoconf v2.9)
 dnl
-dnl  $Id: configure.in,v 1.388 2005/10/23 11:55:31 hno Exp $
+dnl  $Id: configure.in,v 1.389 2005/10/30 21:48:21 serassio Exp $
 dnl
 dnl
 dnl
@@ -13,7 +13,7 @@ AC_CONFIG_SRCDIR([src/main.cc])
 AC_CONFIG_AUX_DIR(cfgaux)
 AM_INIT_AUTOMAKE(squid, 3.0-PRE3-CVS)
 AM_CONFIG_HEADER(include/autoconf.h)
-AC_REVISION($Revision: 1.388 $)dnl
+AC_REVISION($Revision: 1.389 $)dnl
 AC_PREFIX_DEFAULT(/usr/local/squid)
 AM_MAINTAINER_MODE
 
@@ -1351,6 +1351,43 @@ if test -n "$NTLM_AUTH_HELPERS"; then
     echo "NTLM auth helpers built: $NTLM_AUTH_HELPERS"
 fi
 AC_SUBST(NTLM_AUTH_HELPERS)
+
+dnl Select negotiate auth helpers to build
+NEGOTIATE_AUTH_HELPERS=
+AC_ARG_ENABLE(negotiate-auth-helpers,
+[  --enable-negotiate-auth-helpers=\"list of helpers\"
+                          This option selects which proxy_auth negotiate helpers
+                          to build and install as part of the normal build 
+                          process. For a list of available helpers see
+                          the helpers/negotiate_auth directory.],
+[ case "$enableval" in
+  yes) 
+	for dir in $srcdir/helpers/negotiate_auth/*; do
+	    helper="`basename $dir`"
+	    if test -d "$dir" && test "$helper" != CVS; then
+		NEGOTIATE_AUTH_HELPERS="$NEGOTIATE_AUTH_HELPERS $helper"
+	    fi
+	done
+	;;
+  no)
+	;;
+  *)
+	NEGOTIATE_AUTH_HELPERS="`echo $enableval| sed -e 's/,/ /g;s/  */ /g'`"
+	;;
+  esac
+])
+if test -n "$NEGOTIATE_AUTH_HELPERS"; then
+    for helper in $NEGOTIATE_AUTH_HELPERS; do
+	if test -d $srcdir/helpers/negotiate_auth/$helper; then
+	    :
+	else
+	    echo "ERROR: Negotiate Auth helper $helper does not exists"
+	    exit 1
+	fi
+    done
+    echo "Negotiate auth helpers built: $NEGOTIATE_AUTH_HELPERS"
+fi
+AC_SUBST(NEGOTIATE_AUTH_HELPERS)
 
 dnl Select digest auth scheme helpers to build
 DIGEST_AUTH_HELPERS=
@@ -2898,6 +2935,7 @@ AC_CONFIG_FILES([\
 	helpers/basic_auth/NCSA/Makefile \
 	helpers/basic_auth/PAM/Makefile \
 	helpers/basic_auth/SMB/Makefile \
+	helpers/basic_auth/mswin_sspi/Makefile \
 	helpers/basic_auth/YP/Makefile \
 	helpers/basic_auth/getpwnam/Makefile \
 	helpers/basic_auth/multi-domain-NTLM/Makefile \
@@ -2909,6 +2947,9 @@ AC_CONFIG_FILES([\
 	helpers/ntlm_auth/no_check/Makefile \
 	helpers/ntlm_auth/SMB/Makefile \
 	helpers/ntlm_auth/SMB/smbval/Makefile \
+	helpers/ntlm_auth/mswin_sspi/Makefile \
+	helpers/negotiate_auth/Makefile \
+	helpers/negotiate_auth/mswin_sspi/Makefile \
 	helpers/external_acl/Makefile \
 	helpers/external_acl/ip_user/Makefile \
 	helpers/external_acl/ldap_group/Makefile \
