/tmp/cvsZKn66v

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -3,7 +3,7 @@ dnl  Configuration input file for Squid
 dnl
 dnl  Duane Wessels, wessels@nlanr.net, February 1996 (autoconf v2.9)
 dnl
-dnl  $Id: configure.in,v 1.356 2004/07/13 01:01:19 hno Exp $
+dnl  $Id: configure.in,v 1.357 2004/08/30 03:28:45 robertc Exp $
 dnl
 dnl
 dnl
@@ -13,7 +13,7 @@ AC_CONFIG_SRCDIR([src/main.cc])
 AC_CONFIG_AUX_DIR(cfgaux)
 AM_INIT_AUTOMAKE(squid, 3.0-PRE3-CVS)
 AM_CONFIG_HEADER(include/autoconf.h)
-AC_REVISION($Revision: 1.356 $)dnl
+AC_REVISION($Revision: 1.357 $)dnl
 AC_PREFIX_DEFAULT(/usr/local/squid)
 AM_MAINTAINER_MODE
 
@@ -30,6 +30,8 @@ AC_LANG_C
 AC_PROG_CXX
 AM_PROG_CC_C_O
 AC_CANONICAL_HOST
+AM_PROG_LIBTOOL
+AC_LTDL_DLLIB
 
 
 CRYPTLIB=''
@@ -1103,9 +1105,14 @@ if test -n "$AUTH_MODULES"; then
     AUTH_OBJS="auth/lib`echo $AUTH_MODULES|sed -e 's% %.a auth/lib%g'`.a"
     AUTH_LIBS="`echo $AUTH_OBJS|sed -e 's%auth/%%g'`"
 fi
+AUTH_LINKOBJS=
+for module in $AUTH_MODULES; do
+  AUTH_LINKOBJS="$AUTH_LINKOBJS auth/${module}/${module}Scheme.o"
+done
 AC_SUBST(AUTH_MODULES)
-AC_SUBST(AUTH_OBJS)
 AC_SUBST(AUTH_LIBS)
+AC_SUBST(AUTH_LINKOBJS)
+AC_SUBST(AUTH_OBJS)
 
 dnl Select basic auth scheme helpers to build
 BASIC_AUTH_HELPERS=""
@@ -1371,6 +1378,42 @@ AC_ARG_ENABLE(x_accelerator_vary,
 AC_ARG_WITH(filedescriptors,
 [  --with-filedescriptors=NUMBER Force squid to support NUMBER filedescriptors],
 [ squid_filedescriptors_num=$withval ])
+
+# FIXME, try linking in a test program first, then if that fails try probing etc.
+SQUID_CPPUNIT_DIR='cppunit-1.10.0'
+SQUID_CPPUNIT_LA='$(top_builddir)/lib/cppunit-1.10.0/src/cppunit/libcppunit.la' 
+SQUID_CPPUNIT_INC='-I$(top_builddir)/lib/cppunit-1.10.0/include -I $(top_srcdir)/lib/cppunit-1.10.0/include'
+if test -f /usr/include/cppunit/TestCase.h; then
+  echo "using system installed cppunit"
+  SQUID_CPPUNIT_DIR=''
+  SQUID_CPPUNIT_LA='/usr/lib/libcppunit.la'
+  SQUID_CPPUNIT_INC=''
+fi
+AC_ARG_WITH(cppunit-basedir,
+[  --with-cppunit-basedir=/path/to/cppunit-base
+                          Path where the cppunit headers are libraries are found
+			  for unit testing. (defaults to use internal copies -
+			  version 1.10.0)
+			  ],
+[ if test -f $withval/include/cppunit/TestCase.h; then
+	echo "Using cppunit includes from $withval"
+	SQUID_CPPUNIT_INC="-I${withval}/include"
+    else
+	echo "ERROR: Cannot find cppunit at $withval"
+	exit 1
+    fi
+  if test -f $withval/lib/libcppunit.la; then
+	echo "Using cppunit lib from $withval"
+	SQUID_CPPUNIT_LA="-I${withval}/lib/libcppunit.la"
+    else
+	echo "ERROR: Cannot find cppunit at $withval"
+	exit 1
+    fi
+  SQUID_CPPUNIT_DIR=''
+])
+AC_SUBST(SQUID_CPPUNIT_LA)
+AC_SUBST(SQUID_CPPUNIT_INC)
+AC_SUBST(SQUID_CPPUNIT_DIR)
 
 # Force some compilers to use ANSI features
 #
@@ -2609,5 +2652,6 @@ AC_CONFIG_FILES([\
 ])
 
 AC_CONFIG_SUBDIRS(lib/libTrie)
+AC_CONFIG_SUBDIRS(lib/cppunit-1.10.0)
 
 AC_OUTPUT
