Bail out at configure time if invalid --enable-XXXX-helpers=YYYY arguments is used rather than crashing the build process.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -3,7 +3,7 @@ dnl  Configuration input file for Squid
 dnl
 dnl  Duane Wessels, wessels@nlanr.net, February 1996 (autoconf v2.9)
 dnl
-dnl  $Id: configure.in,v 1.279 2002/07/28 21:55:33 hno Exp $
+dnl  $Id: configure.in,v 1.280 2002/08/11 00:50:21 hno Exp $
 dnl
 dnl
 dnl
@@ -11,7 +11,7 @@ AC_INIT(src/main.c)
 AC_CONFIG_AUX_DIR(cfgaux)
 AM_INIT_AUTOMAKE(squid, 2.6-DEVEL)
 AM_CONFIG_HEADER(include/autoconf.h)
-AC_REVISION($Revision: 1.279 $)dnl
+AC_REVISION($Revision: 1.280 $)dnl
 AC_PREFIX_DEFAULT(/usr/local/squid)
 AM_MAINTAINER_MODE
 
@@ -946,6 +946,14 @@ AC_ARG_ENABLE(basic-auth-helpers,
   esac
 ])
 if test -n "$BASIC_AUTH_HELPERS"; then
+    for helper in $BASIC_AUTH_HELPERS; do
+	if test -f $srcdir/helpers/basic_auth/$helper/Makefile.in; then
+		:
+	else
+		echo "ERROR: Basic auth helper $helper does not exists"
+		exit 1
+	fi
+    done
     echo "Basic auth helpers built: $BASIC_AUTH_HELPERS"
 fi
 AC_SUBST(BASIC_AUTH_HELPERS)
@@ -973,6 +981,14 @@ AC_ARG_ENABLE(ntlm-auth-helpers,
   esac
 ])
 if test -n "$NTLM_AUTH_HELPERS"; then
+    for helper in $NTLM_AUTH_HELPERS; do
+	if test -f $srcdir/helpers/ntlm_auth/$helper/Makefile.in; then
+		:
+	else
+		echo "ERROR: NTLM auth helper $helper does not exists"
+		exit 1
+	fi
+    done
     echo "NTLM auth helpers built: $NTLM_AUTH_HELPERS"
 fi
 AC_SUBST(NTLM_AUTH_HELPERS)
@@ -1037,6 +1053,14 @@ AC_ARG_ENABLE(external-acl-helpers,
   esac
 ])
 if test -n "$EXTERNAL_ACL_HELPERS"; then
+    for helper in $EXTERNAL_ACL_HELPERS; do
+	if test -f $srcdir/helpers/external_acl/$helper/Makefile.in; then
+		:
+	else
+		echo "ERROR: NTLM external acl helper $helper does not exists"
+		exit 1
+	fi
+    done
     echo "External acl helpers built: $EXTERNAL_ACL_HELPERS"
 fi
 AC_SUBST(EXTERNAL_ACL_HELPERS)
