Bug #981: sasl_auth doesn't compile with SASL2

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -3,7 +3,7 @@ dnl  Configuration input file for Squid
 dnl
 dnl  Duane Wessels, wessels@nlanr.net, February 1996 (autoconf v2.9)
 dnl
-dnl  $Id: configure.in,v 1.358 2004/08/30 05:12:29 robertc Exp $
+dnl  $Id: configure.in,v 1.359 2004/09/03 21:30:18 hno Exp $
 dnl
 dnl
 dnl
@@ -13,7 +13,7 @@ AC_CONFIG_SRCDIR([src/main.cc])
 AC_CONFIG_AUX_DIR(cfgaux)
 AM_INIT_AUTOMAKE(squid, 3.0-PRE3-CVS)
 AM_CONFIG_HEADER(include/autoconf.h)
-AC_REVISION($Revision: 1.358 $)dnl
+AC_REVISION($Revision: 1.359 $)dnl
 AC_PREFIX_DEFAULT(/usr/local/squid)
 AM_MAINTAINER_MODE
 
@@ -1141,7 +1141,11 @@ AC_ARG_ENABLE(basic-auth-helpers,
 if test -n "$BASIC_AUTH_HELPERS"; then
     for helper in $BASIC_AUTH_HELPERS; do
 	if test -d $srcdir/helpers/basic_auth/$helper; then
-	    :
+	    case $helper in
+	    SASL)
+		    require_sasl=yes
+		    ;;
+	    esac
 	else
 	    echo "ERROR: Basic auth helper $helper does not exists"
 	    exit 1
@@ -1312,6 +1316,24 @@ AC_ARG_WITH(samba-sources,
     fi
 ])
 AC_SUBST(SAMBASOURCES)
+
+dnl Check for Cyrus SASL
+if test "$require_sasl" = "yes"; then
+	AC_CHECK_HEADERS(sasl/sasl.h sasl.h)
+	if test "$ac_cv_header_sasl_sasl_h" = "yes"; then
+		echo "using SASL2"
+		LIBSASL="-lsasl2"
+	else
+		if test "$ac_cv_header_sasl_h" = "yes"; then
+			echo "using SASL"
+			LIBSASL="-lsasl"
+		else
+			echo "ERROR: Neither SASL nor SASL2 found"
+			exit 1
+		fi
+	fi
+	AC_SUBST(LIBSASL)
+fi
 
 dnl Disable "unlinkd" code
 AC_ARG_ENABLE(unlinkd,
