update

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -3,13 +3,13 @@ dnl  Configuration input file for Squid
 dnl
 dnl  Duane Wessels, wessels@nlanr.net, February 1996 (autoconf v2.9)
 dnl
-dnl  $Id: configure.in,v 1.119 1998/04/08 22:59:02 wessels Exp $
+dnl  $Id: configure.in,v 1.120 1998/04/24 05:26:59 wessels Exp $
 dnl
 dnl
 dnl
 AC_INIT(src/main.c)
 AC_CONFIG_HEADER(include/autoconf.h)
-AC_REVISION($Revision: 1.119 $)dnl
+AC_REVISION($Revision: 1.120 $)dnl
 AC_PREFIX_DEFAULT(/usr/local/squid)
 AC_CONFIG_AUX_DIR(cfgaux)
 
@@ -62,19 +62,6 @@ PRESET_CFLAGS="$CFLAGS"
 
 dnl Check for GNU cc
 AC_PROG_CC
-
-dnl Warn if not using GNU cc
-dnl if test $ac_cv_prog_gcc = no; then
-dnl     echo '**************************************************************';
-dnl     echo '**************************************************************';
-dnl     echo '**';
-dnl     echo '**   WARNING:  Squid is only guaranteed to compile with GNU cc.';
-dnl     echo "**   Currently, you're using $CC";
-dnl     echo '**';
-dnl     echo '**************************************************************';
-dnl     echo '**************************************************************';
-dnl sleep 5
-dnl fi
 
 dnl Gerben Wierda <Gerben_Wierda@RnA.nl>
 case "$host" in
@@ -189,7 +176,7 @@ AC_ARG_ENABLE(gnuregex,
 [  --enable-gnuregex       Compile GNUregex],
 [USE_GNUREGEX=$enableval])
 
-AC_ARG_ENABLE(acltree,
+AC_ARG_ENABLE(splaytree,
 [  --enable-splaytree      Use SPLAY trees to store ACL lists],
 [ if test "$enableval" = "yes" ; then
 	echo "ACL lists using SPLAY trees"
@@ -322,6 +309,15 @@ AC_ARG_ENABLE(arp_acl,
 [  --enable-arp-acl        Enable use of ARP ACL lists (ether address)],
 [  if test "$enableval" = "yes" ; then
      echo "ARP ACL lists enabled (ether address)"
+     case "$host" in
+	i386-*-freebsd*)
+	    ;;
+	*)
+	    echo "WARNING: ARP ACL support is designed for FreeBSD and"
+	    echo "WARNING: probably wont work on your $host system"
+	    sleep 10
+	    ;;
+     esac
      AC_DEFINE(USE_ARP_ACL)
    fi
 ])
@@ -359,6 +355,20 @@ AC_ARG_ENABLE(peer-digests,
     AC_DEFINE(SQUID_PEER_DIGEST)
   fi
 ])
+
+dnl Select Error language
+AC_ARG_ENABLE(err-language,
+[  --enable-err-language=lang
+                          Select language for Error pages (see errors dir) ],
+[
+    if test -d errors/$enableval; then
+	ERR_LANGUAGE=$enableval
+    else
+	echo "ERROR! Unknown language $enableval, see errors/"
+	exit 1
+    fi
+ERR_],[LANGUAGE="English"])
+AC_SUBST(ERR_LANGUAGE)
 
 # Force some compilers to use ANSI features
 #
@@ -831,6 +841,7 @@ if test "$SQUID_MAXFD" -lt 512 ; then
     echo "         cache will be very busy.  Please see the FAQ page"
     echo "         http://squid.nlanr.net/Squid/FAQ/FAQ-10.html#filedescriptors"
     echo "	   on how to increase your filedescriptor limit"
+    sleep 10
 fi
 
 dnl Not cached since people are likely to tune this
