Cleanup of winbind header dependencies to correct building with current Samba releases and make migration easier in future (and also backward to older Samba versions if needed)
1. Centralize the headers to include/samba/nsswitch

2. Upgraded the headers to Samba-2.2.7a, without any changes

3. Added a --with-samba-source=... configure option to manually specify
   other headers to use (top level Samba source directory)

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -3,7 +3,7 @@ dnl  Configuration input file for Squid
 dnl
 dnl  Duane Wessels, wessels@nlanr.net, February 1996 (autoconf v2.9)
 dnl
-dnl  $Id: configure.in,v 1.320 2003/02/08 17:06:58 hno Exp $
+dnl  $Id: configure.in,v 1.321 2003/02/11 14:34:31 hno Exp $
 dnl
 dnl
 dnl
@@ -13,7 +13,7 @@ AC_CONFIG_SRCDIR([src/main.cc])
 AC_CONFIG_AUX_DIR(cfgaux)
 AM_INIT_AUTOMAKE(squid, 3.0-DEVEL)
 AM_CONFIG_HEADER(include/autoconf.h)
-AC_REVISION($Revision: 1.320 $)dnl
+AC_REVISION($Revision: 1.321 $)dnl
 AC_PREFIX_DEFAULT(/usr/local/squid)
 AM_MAINTAINER_MODE
 
@@ -1188,6 +1188,24 @@ AC_ARG_ENABLE(mempools,
     AC_DEFINE(DISABLE_POOLS, 1, [Define if you have problems with memPools and want to disable Pools])
   fi
 ])
+
+
+SAMBASOURCES='$(top_srcdir)/include/samba'
+AC_ARG_WITH(samba-sources,
+[  --with-samba-sources=/path/to/samba-source-tree
+                          Path where the correct Samba source files can be
+			  found while building winbind helpers. (defaults to
+			  use internal copies of the headers from Samba-2.2.7)
+			  ],
+[ if test -f $withval/source/nsswitch/winbind_nss_config.h; then
+	echo "Using Samba sources from $withval"
+	SAMBASOURCES="$withval/source"
+    else
+	echo "ERROR: Cannot find Samba sources at $withval"
+	exit 1
+    fi
+])
+AC_SUBST(SAMBASOURCES)
 
 dnl Disable "unlinkd" code
 AC_ARG_ENABLE(unlinkd,
