Bugfixes in configure --enable-xxxx-helper error checking
- Check on digest helpers is missing
- In external acl helper check there is a cut & past error

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -3,7 +3,7 @@ dnl  Configuration input file for Squid
 dnl
 dnl  Duane Wessels, wessels@nlanr.net, February 1996 (autoconf v2.9)
 dnl
-dnl  $Id: configure.in,v 1.280 2002/08/11 00:50:21 hno Exp $
+dnl  $Id: configure.in,v 1.281 2002/08/12 22:23:01 hno Exp $
 dnl
 dnl
 dnl
@@ -11,7 +11,7 @@ AC_INIT(src/main.c)
 AC_CONFIG_AUX_DIR(cfgaux)
 AM_INIT_AUTOMAKE(squid, 2.6-DEVEL)
 AM_CONFIG_HEADER(include/autoconf.h)
-AC_REVISION($Revision: 1.280 $)dnl
+AC_REVISION($Revision: 1.281 $)dnl
 AC_PREFIX_DEFAULT(/usr/local/squid)
 AM_MAINTAINER_MODE
 
@@ -1016,6 +1016,14 @@ AC_ARG_ENABLE(digest-auth-helpers,
   esac
 ])
 if test -n "$DIGEST_AUTH_HELPERS"; then
+    for helper in $DIGEST_AUTH_HELPERS; do
+	if test -f $srcdir/helpers/digest_auth/$helper/Makefile.in; then
+		:
+	else
+		echo "ERROR: digest auth helper $helper does not exists"
+		exit 1
+	fi
+    done
     echo "Digest auth helpers built: $DIGEST_AUTH_HELPERS"
 fi
 AC_SUBST(DIGEST_AUTH_HELPERS)
@@ -1057,7 +1065,7 @@ if test -n "$EXTERNAL_ACL_HELPERS"; then
 	if test -f $srcdir/helpers/external_acl/$helper/Makefile.in; then
 		:
 	else
-		echo "ERROR: NTLM external acl helper $helper does not exists"
+		echo "ERROR: external acl helper $helper does not exists"
 		exit 1
 	fi
     done
