merging changes from SQUID_1_0 branch

diff --git a/scripts/RunAccel.in b/scripts/RunAccel.in
--- a/scripts/RunAccel.in
+++ b/scripts/RunAccel.in
@@ -1,20 +1,22 @@
 #!/bin/sh
 #
-#  $Id: RunAccel.in,v 1.2 1996/04/16 16:37:53 wessels Exp $
+#  $Id: RunAccel.in,v 1.3 1996/05/03 22:56:19 wessels Exp $
 
 # enable HTTP requests on port 80
-set port="-a 80"
+port="-a 80"
 
-PATH=@prefix@/bin:/bin
+prefix=@prefix@
+exec_prefix=@exec_prefix@
+PATH=@bindir@:/bin
 export PATH
 
-if test $#argv = 1 ; then
+if test $# = 1 ; then
 	conf="-f $1"
-	shift;
+	shift
 fi
 
 failcount=0
-while test 1 ; do
+while : ; do
 	echo "Running: squid $port -s $conf >> squid.out 2>&1"
 	start=`date '+%d%H%M%S'`
 	squid $port -s $conf >> squid.out 2>&1
@@ -26,7 +28,7 @@ while test 1 ; do
 		failcount=0
 	fi
 	if test $failcount -gt 5 ; then
-		echo "RunCache: EXITING DUE TO REPEATED, FREQUENT FAILURES"
+              echo "RunCache: EXITING DUE TO REPEATED, FREQUENT FAILURES" >&2
 		exit 1
 	fi
 	sleep 10
diff --git a/scripts/RunCache.in b/scripts/RunCache.in
--- a/scripts/RunCache.in
+++ b/scripts/RunCache.in
@@ -1,18 +1,20 @@
 #!/bin/sh
 #
-#  $Id: RunCache.in,v 1.4 1996/05/01 22:36:22 wessels Exp $
+#  $Id: RunCache.in,v 1.5 1996/05/03 22:56:19 wessels Exp $
 
-PATH=@prefix@/bin:/bin
+prefix=@prefix@
+exec_prefix=@exec_prefix@
+PATH=@bindir@:/bin
 export PATH
 
 conf=""
 if test "$1" ; then
 	conf="-f $1"
-	shift;
+	shift
 fi
 
 failcount=0
-while test 1 ; do
+while : ; do
 	echo "Running: squid -s $conf >> squid.out 2>&1"
 	start=`date '+%d%H%M%S'`
 	squid -s $conf >> squid.out 2>&1
@@ -24,7 +26,7 @@ while test 1 ; do
 		failcount=0
 	fi
 	if test $failcount -gt 5 ; then
-		echo "RunCache: EXITING DUE TO REPEATED, FREQUENT FAILURES"
+              echo "RunCache: EXITING DUE TO REPEATED, FREQUENT FAILURES" >&2
 		exit 1
 	fi
 	sleep 10
